#!/bin/sh

DOTFILES="$HOME/dotfiles"

touch "$HOME"/.psqlrc.local

# install antidote
if which brew >/dev/null 2>&1; then
	brew install antidote || brew upgrade antidote
else
	git clone --depth=1 https://github.com/mattmc3/antidote.git $HOME/.antidote
	
fi
# antibody bundle <"$DOTFILES/antibody/bundles.txt" >~/.zsh_plugins.sh
# antibody update

[ "$(uname -s)" != "Darwin" ] && exit 0
sed -i ''  "s;/Users/brunoazevedo;$HOME;g" \
	"$DOTFILES"/iterm2/com.googlecode.iterm2.plist
defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "$DOTFILES/iterm2"
defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

# cp "$DOTFILES"/iterm2/fonts/**/*.ttf "$HOME"/Library/Fonts
