#!/bin/sh

touch "$HOME"/.psqlrc.local

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

[ -d $HOME/.vim/undo ] || mkdir $HOME/.vim/undo

# install antibody
if which brew >/dev/null 2>&1; then
	brew install getantibody/tap/antibody || brew upgrade antibody
else
	curl -sL https://git.io/antibody | sh -s
fi
antibody bundle <"$HOME/.dotfiles/antibody/bundles.txt" >~/.zsh_plugins.sh
antibody update
